# Generated by Django 5.2.4 on 2025-07-23 19:39

import Channel.models
import LibertyWave.storage_backend
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Channel', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='logo',
            field=models.ImageField(null=True, storage=LibertyWave.storage_backend.PrivateMediaStorage(), upload_to=Channel.models.thumbnail_upload_path, validators=[Channel.models.validate_image_size]),
        ),
    ]
