# Generated by Django 5.2.4 on 2025-07-06 09:37

import LibertyWave.storage_backend
import Video.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Channel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('video_file', models.FileField(storage=LibertyWave.storage_backend.PrivateMediaStorage(), upload_to=Video.models.video_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'ogg'])])),
                ('thumbnail', models.ImageField(storage=LibertyWave.storage_backend.PrivateMediaStorage(), upload_to=Video.models.thumbnail_upload_path)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='Channel.channel')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
