# Generated by Django 5.2.4 on 2025-07-23 19:28

import LibertyWave.storage_backend
import Video.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Video', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(storage=LibertyWave.storage_backend.PrivateMediaStorage(), upload_to=Video.models.thumbnail_upload_path, validators=[Video.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(storage=LibertyWave.storage_backend.PrivateMediaStorage(), upload_to=Video.models.video_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'ogg']), Video.models.validate_file_size]),
        ),
    ]
